### ISSUE TITLE
organiza as constantes

### ISSUE THREAD

**Issue by JoseMagno** [MarinaFroes/Palindrome-Checker#1]
codigo com constantes espalhadas, tipo:
`checkedResult.innerHTML = "Ops! There's nothing to check! Try to type something.";
    checkedResult.style.backgroundColor = "#900";`
se torna difícil de manter. 

uma boa pratica é tentar separar esses valores em constantes no começo do arquivo (ou funcao) e depois utilizar.
Exemplo:
`
const ERROR_MSG =  "Ops! There's nothing to check! Try to type something.";
const DEFAULT_BG_COLOR = "#900;"
...

checkedResult.innerHTML = ERROR_MSG;
checkedResult.style.backgroundColor = DEFAULT_BG_COLOR;
`

https://github.com/MarinaFroes/Palindrome-Checker/blob/a1671e2fe7a0819115094b2c18fbb357cae59e23/main.js#L7

**Comment by MarinaFroes** [comment]
Corrigido. Obrigada!
