### ISSUE TITLE
organizar o projeto em diretorios

### ISSUE THREAD

**Issue by JoseMagno** [MarinaFroes/Palindrome-Checker#3]
esse projeto 'e pequeno, entao  a organizacao do projeto n~ao 'e tao importante.
Ainda assim, seria interessante manter uma estrutura padrao. algo como:
/
   /src
      main.js
   /css
      style.css
   README.md
   favicon
   index.html

o /src vem de source. geralmente 'e onde a gente adiciona os arquivos javascript.
existem milhoes formas de organizar um projeto. essa 'e uma bem simples que pode ser usada nesse caso. 
Lembra que mudando a organizacao aqui vai precisar alterar o arquivo index.html pra apontar pro local correto.

**Comment by MarinaFroes** [comment]
Feito. Obrigada!
